version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: login docker
          command: echo $DOCKER_PASS| docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build multi arch docker
          command: | 
            DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform
            linux/arm64,linux/amd64,linux/386,linux/riscv64 --push -t $DOCKER_IMAGE:latest .
    filtered:
      branches:
        only: 
          master
