version: 2
jobs:
  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: login docker
          command: echo $DOCKER_PASS| docker login -u $DOCKER_USER --password-stdin
      - run: |
          docker buildx build \
            --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
            --tag $DOCKER_IMAGE:latest .
    filtered:
      branches:
        only: 
          master
